import {expect,it} from 'vitest';import {relationshipGraphSchema} from '../packages/protocol/relationships';import {graph} from './relationship-data';
it('validates typed edges and rejects integrity violations',()=>{expect(relationshipGraphSchema.safeParse(graph).success).toBe(true);const bad=structuredClone(graph);bad.edges[0]!.edge_id='e2';expect(relationshipGraphSchema.safeParse(bad).success).toBe(false);bad.edges[0]!.edge_id='e1';bad.edges[0]!.to='missing';expect(relationshipGraphSchema.safeParse(bad).success).toBe(false);});
it('rejects containment cycles, duplicate semantic edges and invalid transitions',()=>{const cycle=structuredClone(graph);cycle.edges.push({...cycle.edges[3]!,edge_id:'cycle',from:'cabinet',to:'sink'});expect(relationshipGraphSchema.safeParse(cycle).success).toBe(false);const dup=structuredClone(graph);dup.edges.push({...dup.edges[1]!,edge_id:'dup'});expect(relationshipGraphSchema.safeParse(dup).success).toBe(false);const bad=structuredClone(graph);bad.edges[4]!.endpoints=['spaceA'];expect(relationshipGraphSchema.safeParse(bad).success).toBe(false);});
it('rejects reversed symmetric duplicates, wrong endpoint kinds and inverse containment duplicates',()=>{
 const g=structuredClone(graph);g.edges.push({...g.edges[0]!,edge_id:'reverse',from:'wallL',to:'bottom'});expect(relationshipGraphSchema.safeParse(g).success).toBe(false);
 const t=structuredClone(graph);t.edges[4]!.endpoints=['bottom','spaceA'];expect(relationshipGraphSchema.safeParse(t).success).toBe(false);
 const d=structuredClone(graph);d.edges.push({...d.edges[2]!,edge_id:'inverse',from:'sink',to:'bottom',type:'contains'});expect(relationshipGraphSchema.safeParse(d).success).toBe(false);
});
it('rejects duplicate nodes, sources, stale evidence, unreviewed and naming verified facts',()=>{
 const d=structuredClone(graph);d.nodes.push({...d.nodes[0]!});expect(relationshipGraphSchema.safeParse(d).success).toBe(false);
 const s=structuredClone(graph);s.sources.push({...s.sources[0]!});expect(relationshipGraphSchema.safeParse(s).success).toBe(false);
 const e=structuredClone(graph);e.edges[0]!.provenance.source_revision='old';expect(relationshipGraphSchema.safeParse(e).success).toBe(false);
 const n=structuredClone(graph);n.edges[0]!.provenance.method='inferred_from_naming';expect(relationshipGraphSchema.safeParse(n).success).toBe(false);
});
it('rejects physical links to space nodes and nonsensical required capabilities',()=>{const d=structuredClone(graph);d.edges[0]!.to='spaceA';expect(relationshipGraphSchema.safeParse(d).success).toBe(false);const p=relationshipGraphSchema.parse(graph);p.requirements=[{capability:'component_hierarchy',node_id:'bottom',types:['supports']}];expect(relationshipGraphSchema.safeParse(p).success).toBe(false);});
it('supports typed directed support/open/access and explicit rejected evidence without generic related_to',()=>{const g=relationshipGraphSchema.parse(graph);g.edges.push({...g.edges[0]!,edge_id:'support',type:'supports'});g.edges.push({...g.edges[4]!,edge_id:'opening',type:'opens_to',endpoints:undefined});g.edges.push({...g.edges[4]!,edge_id:'access',type:'accesses',endpoints:undefined});expect(relationshipGraphSchema.safeParse(g).success).toBe(true);g.edges[0]!.verification={state:'rejected',reviewer:'owner',timestamp:'2026-10-05T04:00:00.000Z',note:'Rejected by review'};expect(relationshipGraphSchema.safeParse(g).success).toBe(true);});
